DECLARE @MESATUAL VARCHAR(30) = '201806';
DECLARE @MESSUPER VARCHAR(30) = '201807';


WITH PRIMATH AS
(

SELECT ATUAL.*, ISNULL(ANTERIOR.[RO STATUS],'') AS RO_STATUS_ANTERIOR,

------- PENDENTE
CASE ATUAL.[SERVICE_PERFORMED]
	WHEN 'LEGAL PROVISION' THEN 'J'
	WHEN 'PROCESSO JUDICIAL' THEN 'J'
	WHEN 'HONORARIOS ADVOCATICIOS' THEN 'J'
	WHEN '_PROCESSO JUDICIAL' THEN 'J'
	WHEN '_HONORARIOS ADVOCATICIOS' THEN 'J'
	WHEN '_DESPESA COM SINISTRO JUDICIAL' THEN 'J'
	WHEN 'RESSARCIMENTO' THEN 'RESS'
	WHEN 'SALVADOS' THEN 'SALV'
	WHEN 'DESPESA LOGISTICA - SALVADOS' THEN 'DESPESA LOG'
	WHEN 'DESPESAS DE SALVADOS' THEN 'DESPESAS SALV'
				
	ELSE 'A' END TP_SINISTRO,


--CONVERT(MONEY,ISNULL(PENANTERIOR.[VALOR],0))/100 AS PENDENTE,
CONVERT(MONEY,ISNULL(REPLACE(PENANTERIOR.[VALOR], ',','.'),0)) AS PENDENTE,

----------------
----------INICIAL

	CASE ATUAL.[BUSINESS TYPE] 

		WHEN 'B&W' THEN
				CASE SUBSTRING(ATUAL.[DATA_CRIACAO_RO],7,4) + SUBSTRING(ATUAL.[DATA_CRIACAO_RO],4,2)
					WHEN @MESATUAL THEN 385 ELSE CONVERT(MONEY,ISNULL(REPLACE(PENANTERIOR.[VALOR], ',','.'),0)) END 
		WHEN 'AUTOS' THEN
				CASE SUBSTRING(ATUAL.[DATA_CRIACAO_RO],7,4) + SUBSTRING(ATUAL.[DATA_CRIACAO_RO],4,2)
					WHEN @MESATUAL THEN 2255 ELSE CONVERT(MONEY,ISNULL(REPLACE(PENANTERIOR.[VALOR], ',','.'),0)) END
	ELSE CONVERT(MONEY,ISNULL(REPLACE(PENANTERIOR.[VALOR], ',','.'),0)) END AS INICIAL,

------------------
------------FINAL

	CASE ATUAL.[RO STATUS]

		WHEN 'OPEN' THEN 385 ELSE CONVERT(MONEY,ISNULL(ATUAL.[TOTAL],0))/100 END FINAL,

------------------
-----------REABERTURA

IIF(

(CASE ANTERIOR.[RO STATUS] 
	WHEN 'CLOSED' THEN 'S'
	WHEN 'REJECT' THEN 'S'
ELSE 'N' END ) = 'S'

AND 

( CASE ATUAL.[RO STATUS]
		WHEN 'OPEN' THEN 'S'
		WHEN 'PAID' THEN 'S'	
		WHEN 'COMPLETED PAYMENT PENDING' THEN 'S'	
		WHEN 'PAYMENT ORDERED' THEN 'S'	
	ELSE 'N' END) = 'S', 

'S','N') AS REABERTURA





FROM		[YTD_CLAIMS].[DA].[TBTW_TWG_CLAIMS_FULL_2] AS ATUAL
LEFT JOIN   [YTD_CLAIMS].[DA].[PENDENTE_ANTERIOR] AS PENANTERIOR ON ATUAL.[RO EVENT ID] = PENANTERIOR.[RO_EVENT_ID]
LEFT JOIN	[YTD_CLAIMS].[DA].[TBTW_TWG_CLAIMS_FULL] AS ANTERIOR
ON ATUAL.[RO EVENT ID] = ANTERIOR.[RO EVENT ID] 
WHERE 
	IIF(ISNULL(ANTERIOR.[RO STATUS],'')  IN ('PAID','REJECTED','CLOSED')
			   AND ATUAL.[RO STATUS]     IN ('PAID','REJECTED','CLOSED') 
			   AND  ISNULL(ANTERIOR.[RO STATUS],'') = ATUAL.[RO STATUS],'S','N')='N'
	           AND  ATUAL.[RO EVENT ID] IS NOT NULL
			   AND (SUBSTRING(ATUAL.[DATA_CRIACAO_RO],7,4) + SUBSTRING(ATUAL.[DATA_CRIACAO_RO],4,2)) <> '201807'--(@MESSUPER)


			   

)



(SELECT *,

IIF((SUBSTRING([DATA_CRIACAO_RO],7,4) + SUBSTRING([DATA_CRIACAO_RO],4,2))= @MESATUAL
AND TP_SINISTRO = 'A',INICIAL,0) AS VALOR_AVISO,

IIF(TP_SINISTRO = 'A'AND [RO STATUS] NOT IN ('PAID','REJECTED','CLOSED'), FINAL-INICIAL,0)
+ 
IIF(TP_SINISTRO = 'A'AND [RO STATUS] IN ('PAID'), FINAL-INICIAL,0) AS VALOR_AJUSTE,


IIF((SUBSTRING([DATA_CRIACAO_RO],7,4) + SUBSTRING([DATA_CRIACAO_RO],4,2))= @MESATUAL
AND TP_SINISTRO = 'A'AND [RO STATUS] IN ('REJECTED','CLOSED'), INICIAL,0) 

+ 

IIF( [PENDENTE] <> 0 AND TP_SINISTRO = 'A'AND [RO STATUS] IN ('REJECTED','CLOSED'), INICIAL,0)

AS VALOR_CANCELAMENTO,

IIF(TP_SINISTRO = 'A'AND [RO STATUS] IN ('PAID'), FINAL,0) AS VALOR_PAGO,


IIF( TP_SINISTRO = 'A'AND [RO STATUS] IN ('COMPLETED PAYMENT PENDING','OPEN','PAYMENT ORDERED','PENDING'), FINAL,0)  AS PSL,


----- INCORRIDO

IIF((SUBSTRING([DATA_CRIACAO_RO],7,4) + SUBSTRING([DATA_CRIACAO_RO],4,2))= @MESATUAL
AND TP_SINISTRO = 'A',INICIAL,0)

+
IIF(TP_SINISTRO = 'A'AND [RO STATUS] NOT IN ('PAID','REJECTED','CLOSED'), FINAL-INICIAL,0)
+ 
IIF(TP_SINISTRO = 'A'AND [RO STATUS] IN ('PAID'), FINAL-INICIAL,0)

-

IIF((SUBSTRING([DATA_CRIACAO_RO],7,4) + SUBSTRING([DATA_CRIACAO_RO],4,2))= @MESATUAL
AND TP_SINISTRO = 'A'AND [RO STATUS] IN ('REJECTED','CLOSED'), INICIAL,0) 

- 

IIF( [PENDENTE] <> 0 AND TP_SINISTRO = 'A'AND [RO STATUS] IN ('REJECTED','CLOSED'), INICIAL,0)

AS INCORRIDO



FROM PRIMATH)


